id: 824c031688b145f3b4850d53290dbbd1
initial_creation_type: ocr
source_metadata:
  volumes:
    d8941b78eda5438bb17f39d8a76c047d:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
